on:
  rss:
    url:
      - https://unity3d.com/unity/beta/latest.xml
      - https://unity3d.com/unity/releases.xml
    config:
      filterOutputs:
        title: 1
      limit: 1
jobs:
  dispatch:
    name: Repository Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Parse released version
        run: |
          version=`echo '${{ on.rss.outputs.title }}' | cut -d ' ' -f2`
          echo "version=$version" >> $GITHUB_ENV | tee
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mob-sakai/docker
          token: ${{ secrets.WORKFLOW_TOKEN }}
          event-type: build_all
